### PR TITLE
Hello

### PR DESCRIPTION
**Pull request by Dosx001**
Hey, I haven't heard from you. I tried getting in contact with you through Linkedin but you haven't responded. I did ping you in the other pull request but no luck there. The only way I have been able to get in contact with you is with pull requests so here is another one lol.

I still want to work on this project, but I've just been busy working on other projects. There are a few more features I want to add and create some safety nets for the user.

So check out some of the changes I made in the other pull request. They're some pretty cool changes and give your feedback. 😃

### CODE REVIEW

**Comment by Jintin** [comment]
Thanks for following up, ya, actually I saw your message on linkedin but soon the message is gone so I guess you delete it on your end? or still working on something. Maybe you can ping me again and let's add friend?

The problem for me is the message on this change is too massive to catch up, for example you create several pr and keep pushing things into it and also with the discussion or progress update. It's a bit hard to keep an eye on every change you made. But I do really appreciate your contribute. Maybe just let me know when you finish on your idea? or let's do it step by step if you have several improve idea?

**Comment by Jintin** [comment]
And now which pr should I look at for example?

**Comment by Dosx001** [comment]
@Jintin Just look at pr #4. That's where all my comments and commits are at. Can you send me a request on LinkedIn? I can't resend my request. 

Here's my LinkedIn https://www.linkedin.com/in/andresrodriguezmichel/

**Comment by Jintin** [comment]
Screen Shot 2021-01-20 at 11 33 48 AM
The notify still not work but I manually check this time. And linkedIn seems hard to use as well can you see my message on linkedIn?

**Pull request closed without merging**
